#ifndef CELLS_EVOLUTION_INCLUDE_CELLSEVO_GRAPHICS_H_
#define CELLS_EVOLUTION_INCLUDE_CELLSEVO_GRAPHICS_H_

#include "graphics/drawer.h"
#include "graphics/camera.h"

#endif //CELLS_EVOLUTION_INCLUDE_CELLSEVO_GRAPHICS_H_
