#ifndef CELLS_EVOLUTION_INCLUDE_CELLSEVO_CORE_GENES_H_
#define CELLS_EVOLUTION_INCLUDE_CELLSEVO_CORE_GENES_H_

namespace cells_evo::core {
class Gene {

};
}

#endif //CELLS_EVOLUTION_INCLUDE_CELLSEVO_CORE_GENES_H_
